### ISSUE TITLE
Is wfrog abandonware?

### ISSUE THREAD

**Issue by cthart** [wfrog/wfrog#152]
The last code commits were made back in the beginning of 2018, while the last issue update (with no fix in sight for the Google Charts API) was made over 2 years ago.

Any update(s)?

**Comment by markblinkhorn** [comment]
I have rewritten the graphing routines to use the Quickchart API - it isn't a 'drop-in' replacement. I have also modified the WESTEP protocol to use MQTT at the transport layer. My code has now diverged so widely from the original fork that I do not know how to update *this* project - even assuming there would be any interest if I did.

**Comment by jpuigsegur** [comment]
Hi @cthart 
I am one of the original creators of the project and I am running quite successfully two weather stations using wfrog, and another one indirectly.
I would like to say that this is not abandonware although the lack of activity during the last years might suggest otherwise.
@markblinkhorn: There's always interest in collaborations, specially if one of them addresses the main issue that this software currently has, which is the deprecation of Google Charts API. 
Other than this looming issue, the software itself is working quite successfully and this for sure is one of the reasons of the lack of activity. 
Jordi.

**Comment by markblinkhorn** [comment]
Hi @jpuigsegur 
Happy to collaborate. Just let me know how ;)
Mark

**Comment by jpuigsegur** [comment]
@markblinkhorn: Any contribution is always more than welcome, however right now an alternative for Google Charts would be the most appreciated. Is there any way for you to make a pull request for the change to Quickchart API? or if not is there any way to see your fork and evaluate how it could be merged into wfrog?

**Comment by markblinkhorn** [comment]
@jpuigsegur: I have attempted to create a pull request - but I have no idea whether it has worked. If this is no good then I can zip everything up and let you see that. Somehow...

**Comment by jpuigsegur** [comment]
@markblinkhorn: So far it looks like the code has arrived. Give me some days to review it and I'll try to integrate.
BTW, I've checked http://weather.smbconsult.co.uk:7680/ and the graphs look quite nice. Very much in wfrog's style !
I am also closing this issue.
